/* 

Planet names
============
Description: 
Contains list of planet names chosen at random for the game.

*/

// List of planet graphics
const planetGraphics = [
    'earth1',
    'earth2',
    'earth3',
    'earth4',
    'jupiter',
    'mars',
    'mercury',
    'neptune',
    'saturn',
    'saturn2',
    'uranus',
    'venus',
]

// List of planet names (adapted from https://perchance.org/scifi-planet-name)
const planetNames = [
    'Stratos',
    'Persephone',
    'Elysium',
    'Realm',
    'Eldred',
    'Abraxus',
    'Marduk',
    'Zyzyx',
    'Bhuta',
    'Charnel',
    'Glebe',
    'Pyro',
    'Pyroborea',
    'Phoenix',
    'Cog',
    'Spitfire',
    'Ent',
    'Sylth',
    'Shrike',
    'Mana',
    'Sacrifice',
    'Desecration',
    'Nether',
    'Jabal Tariq',
    'Nuevo Andalucía',
    'La Linea',
    'Med',
    'Porto',
    'Abol',
    'Abonsam',
    'Abuk',
    'Achaman',
    'Achimi',
    'Achuguayo',
    'Achuhucanac',
    'Addis',
    'Adroa',
    'Aeldra',
    'Aeolus',
    'Aerilon',
    'Aero',
    'Aether',
    'Aethon ',
    'Aganju',
    'Agares',
    'Agartha',
    'Agé',
    'Agouto',
    'Ahankar',
    'Aim',
    'Aine',
    'Ainu',
    'Aion',
    'Aja',
    'Aklan',
    'Akna ',
    'Ala',
    'Alatangana',
    'Aldabra',
    'Aldebaran',
    'Alef',
    'Alfheim',
    'Algid',
    'Alicanto ',
    'Alkonost',
    'Allocer',
    'Alomkik',
    'Altair',
    'Althea',
    'Altura',
    'Am-heh',
    'Amateru',
    'Ambisagrus ',
    'Amdusias',
    'Amel',
    'Amerind',
    'Amesemi',
    'Ammit',
    'Ampere',
    'Anael',
    'Anahit ',
    'Anann ',
    'Anansi',
    'Anat',
    'Andjety',
    'Andros',
    'Aneris',
    'Angel',
    'Angus',
    'Anhur',
    'Anput',
    'Antioch',
    'Anubis',
    'Anuket',
    'Anyanwu',
    'Apis',
    'Apogee',
    'April',
    'Arachne ',
    'Araki ',
    'Aramazd ',
    'Arawn',
    'Aray ',
    'Arber',
    'Arbuda',
    'Arcadia',
    'Archangel',
    'Arcangelo',
    'Arensnuphis',
    'Argo ',
    'Argos',
    'Argus',
    'Ariane',
    'Arianrhod ',
    'Arieka',
    'Ariel',
    'Armageddon',
    'Arnakuagsak',
    'Artemis',
    'Arve',
    'Arvebalva ',
    'Asase Ya',
    'Asgard',
    'Ash',
    'Asmodeus',
    'Astaroth',
    'Astarte',
    'Asteria',
    'Asura',
    'Asye',
    'Ataksak',
    'Aten',
    'Athena',
    'Athos',
    'Atman',
    'Attalia',
    'Attis',
    'Atum',
    'Aureate',
    'Auriga',
    'Aurora',
    'Avalon',
    'Avenoir',
    'Avesta',
    'Avidya',
    'Awasis',
    'Awilix',
    'Ayao',
    'Azimuth',
    'Ba-Pef',
    'Babel',
    'Babi',
    'Baidi',
    'Baiduri',
    'Balaho',
    'Balam',
    'Ballybran',
    'Baltia',
    'Balungan',
    'Banebdjedet',
    'Barajeel',
    'Barbatos ',
    'Barghest',
    'Barradas',
    'Basilisk ',
    'Bastet',
    'Bat',
    'Battabara',
    'Beaumonde',
    'Beher',
    'Belhor',
    'Bélisama  ',
    'Bellerophon',
    'Beltane',
    'Belzagor',
    'Bendis',
    'Benthos',
    'Beowulf',
    'Berith',
    'Bernadette',
    'Bes',
    'Beth',
    'Bifrost',
    'Big Dog',
    'Bileth',
    'Bivrost',
    'Bluish',
    'Boann ',
    'Bodhi',
    'Boinayel  ',
    'Boketto ',
    'Bomazi',
    'Boreal',
    'Botany',
    'Brahmapura',
    'Bran  ',
    'Brasil',
    'Bride',
    'Brigid',
    'Brimir',
    'Brittia',
    'Bronson',
    'Brownish',
    'Bugid',
    'Buné ',
    'Bunzi',
    'Buraq ',
    'Buru  ',
    'Cabal',
    'Cadence',
    'Caladan',
    'Caladrius ',
    'Caldera',
    'Caleuche  ',
    'Callisto',
    'Camaxtli ',
    'Camulus ',
    'Canaan',
    'Candela',
    'Canid',
    'Canopus',
    'Caprica',
    'Castiana',
    'Caswallawn ',
    'Catubodua ',
    'Cavus',
    'Celeschul ',
    'Celestia',
    'Cerberus',
    'Ceridwen ',
    'Cernunnos',
    'Cetan',
    'Chac Chel',
    'Chantico',
    'Chīkǔ',
    'Chill',
    'Chīmalmā',
    'Chirakan-Ixmucane',
    'Chorus',
    'Chronos',
    'Chthon',
    'Chu',
    'Chura  ',
    'Cibola',
    'Cicolluis ',
    'Cihuacōātl',
    'Clouds',
    'Cōātlīcue',
    'Cocidius ',
    'Cockaigne',
    'Cocoon',
    'Constellation',
    'Corneria',
    'Coronis',
    'Corvi',
    'Corvus',
    'Coyolxāuhqui',
    'Crocell',
    'Crocotta ',
    'Cronus',
    'Cruinlagh  ',
    'Crux',
    'Cu Sith',
    'Cuptor  ',
    'Cyclades',
    'Cygnus',
    'Cyteen',
    'Daeva',
    'Dagon',
    'Danu ',
    'Dantalion',
    'Darkover',
    'Dawn',
    'Daya',
    'Dedun',
    'Delphi',
    'Deluge',
    'Demeter',
    'Denka',
    'Deva',
    'Diablo',
    'Diamant',
    'Dianmu',
    'Dimidium  ',
    'Dione',
    'Dionysus',
    'Dirt',
    'Dis',
    'Discordia',
    'Dismal',
    'Ditsö̀  ',
    'Diya',
    'Dog',
    'Doisac',
    'Doomsday',
    'Dopere  ',
    'Dosadi ',
    'Downbelow',
    'Downfall',
    'Dragon ',
    `Dragon's Egg`,
    'Drake',
    'Draugr',
    'Dreary',
    'Drogon',
    'Dulcinea  ',
    'Dunkirk',
    'Dusk',
    'Dust',
    'Dzelarhons',
    'Eburonia  ',
    'Eclipse',
    'Ehecatl',
    'Eiger  ',
    'Eight Pillars',
    'Ekron',
    'Ekwensu',
    'El Dorado',
    'Eligos',
    'Elysia',
    'Elysium',
    'Emotan',
    'Enlil',
    'Eos',
    'Eostre',
    'Epidaurus ',
    'Epona ',
    'Equinox',
    'Eris',
    'Ermine',
    'Erna',
    'Eros',
    'Erythro',
    'Eshu',
    'Eternia ',
    'Etheria',
    'Euryale',
    'Evenfall',
    'Eventide',
    'Eyeke  ',
    'Ezra',
    'Fafnir',
    'Falias',
    'Falkor',
    'Famn',
    'Far Away',
    'Farpoint',
    'Faso',
    'Faun',
    'Favn',
    'Feng Huang ',
    'Fēngshén',
    'Fennec',
    'Fenrir ',
    'Fhloston Paradise',
    'Fimbul',
    'Finias',
    'Finisterre',
    'Fiorina',
    'Firgun',
    'Firmament',
    'Firn',
    'Flâner',
    'Flauros',
    'Fleed',
    'Focalor',
    'Fold  ',
    'Folia',
    'Forlorn',
    'Forsaken',
    'Fortitude',
    'Fortitudo ',
    'Fortuna',
    'Freyr',
    'Frigg',
    'Frozen',
    'Fury',
    'Furya',
    'Fusang',
    'Gaia',
    'Galatea ',
    'Ganesha',
    'Garm',
    'Garmilas ',
    'Gathas',
    'Gelgid',
    'Genesis',
    'Ghibalb',
    'Gibeon',
    'Glas wen ',
    'Gleti',
    'Gobi',
    'Gobind',
    'Golgotha',
    'Gomorrah',
    'Gor',
    'Gorgon',
    'Gorias',
    'Gorta',
    'Goya',
    'Gravity',
    'Gremory',
    'Grendel',
    'Griffin ',
    'Groom',
    'Guanyin',
    'Guarani  ',
    'Guayota',
    'Gurun',
    'Gurzil',
    'Gusion',
    'Ha',
    'Hahava',
    'Haik  ',
    'Hairu  ',
    'Haishen',
    'Haku',
    'Halla  ',
    'Halvmörk',
    'Hämarik  ',
    'Hapi',
    'Harpy ',
    'Hathor',
    'Hawaiki',
    'Hearth',
    'Heaven',
    'Hecuba',
    'Hedetet',
    'Heimdall',
    'Heka',
    'Helheim',
    'Helghan',
    'Helios',
    'Hell',
    'Helliconia',
    'Hemen',
    'Hemsut',
    'Heqet',
    'Hermanubis',
    'Heryshaf',
    'Heshen',
    'Hesikos ',
    'Hestia',
    'Hiʻiaka',
    'Hiisi ',
    'Hina',
    'Hoarfrost',
    'Holda ',
    'Home',
    'Hoʻohokukalani',
    'Horus ',
    'Hound',
    'Hretha',
    'Hu',
    'Hugin',
    'Huhuva',
    'Huixtocihuatl',
    'Hydra',
    'Hydros',
    'Hyperborea',
    'Hyperion',
    'Hyvä',
    'Iabet',
    'Iapetus',
    'Iat',
    'Ice',
    'Independence',
    'Indra',
    'Iolaus  ',
    'Iomere',
    'Ipotane ',
    'Ireta ',
    'Irkalla',
    'Isagel  ',
    'Iscander',
    'Ishkur',
    'Ishtar',
    'Isli  ',
    'Iszm',
    'Ixchel',
    'Ixtab',
    'Jabulqa',
    'Jabulsa',
    'Jambhala',
    'Jansky',
    'Jebus  ',
    'Jericho',
    'Jingshen',
    'Jotun',
    'Jotunheim',
    `K'awiil`,
    'Kadlu',
    'Kafziel',
    'Kahiko',
    'Karkadann ',
    'Karma',
    'Kaunis',
    'Kavian  ',
    'Kebechet',
    'Kerbin',
    'Kererū  ',
    'Khalsa',
    'Kharak',
    'Khenti-kheti',
    'Kherty',
    'Khonsu',
    'Kinmoku',
    'Kishi ',
    'Kitezh',
    'Koan',
    'Kobol ',
    'Kokh Kox',
    'Komorebi',
    'Kothar-wa-Khasis',
    'Kraken ',
    'Kráľomoc  ',
    'Krieg',
    'Krishna',
    'Krodg',
    'Kubera',
    'Kunlun',
    'Kvasir',
    'Kvenland',
    'Kyrian',
    `La'a Maomao`,
    'Lagash ',
    'Lagom',
    'Lagrange',
    'Laliguran',
    'Laputa',
    'Leaf',
    'Leera',
    'Leishen',
    'Leklsullun  ',
    'Lemuria',
    'Lete  ',
    'Lethe',
    'Leto',
    'Leucetius ',
    'Liban ',
    'Lilac',
    'Lilo',
    'Litost',
    'Lockheed',
    'Loki',
    'Lona',
    'Longma ',
    'Longshen',
    'Lono',
    'Luna',
    'Lux',
    'Maahes',
    'Maat',
    'Macbeth ',
    'Macha ',
    'Madalitso  ',
    'Madriu  ',
    'Maeping  ',
    'Mafdet',
    'Magec',
    'Magor  ',
    'Magrathea ',
    'Mahāpadma',
    'Maher',
    'Mandala',
    'Mandulis',
    'Manticore',
    'Mantra',
    'March',
    'Marduk',
    'Mare',
    'Marinus',
    '  orig=sea synonym',
    'Marshal',
    'Mastika  ',
    'Mau',
    'Mawu',
    'Maya ',
    'Medea',
    'Medjed',
    'Mefitis ',
    'Mehen',
    'Melisma',
    'Menehune',
    'Meret',
    'Mermaid ',
    'Meropis',
    'Meskhenet',
    'Metis',
    'Metztli',
    'Michael',
    'Mictēcacihuātl',
    'Midgard',
    'Midnight',
    'Mimas',
    'Minerva ',
    'Mintome  ',
    'Miron',
    'Mist',
    'Mist Flow',
    'Mnemosyne',
    'Mnevis',
    'Moh',
    'Moneiba',
    'Montu',
    'Moth',
    'Mukuru',
    'Mulungu',
    'Murias',
    'Murmur',
    'Murmux',
    'Mushen',
    'Muspelheim',
    'Mustela ',
    'Mut',
    'Nabu',
    'Nachtkrapp ',
    'Nachtwacht  ',
    'Nacon',
    'Nacre',
    'Nadir',
    'Namaka',
    'Naqaỹa  ',
    'Naraka',
    'Naron  ',
    'Near',
    'Nebtuwi',
    'Nehalennia',
    'Neit',
    'Neith',
    'Nemesis',
    'Nemty',
    'Nephthys',
    'Neri  ',
    'Nerrivik',
    'Nesoi',
    'Nessus',
    'Newton',
    'Nibbana',
    'Nibiru ',
    'Nidor ',
    'Niflheim',
    'Niflhel',
    'Nightfall',
    'Nihil',
    'Nimbus',
    'Nineveh',
    'Nirarbuda',
    'Nirn ',
    'Nirvana',
    'Njoku Ji ',
    'Nod',
    'Noifasui  ',
    'Nomkhubulwane',
    'Norumbega',
    'Nova',
    'Nujalik',
    'Nysa',
    'Nyx',
    'Oba ',
    'Obatala ',
    'Obliquity',
    'Octave',
    'Oggun ',
    'Oghene',
    'Olympia',
    'Olympus',
    'Omega',
    'Omicron',
    'Onias',
    'Onism',
    'Orthe',
    'Orthrus ',
    'Orunmila ',
    'Osebo',
    'Osiris',
    'Ostinato',
    'Ourea',
    'Ouroboros',
    'Ovates',
    'Oxomoco',
    'Paimon',
    'Paititi',
    'Pakaa',
    'Palias',
    'Pallas',
    'Panchaia',
    'Pandora',
    'Pandæmonium',
    'Pangu',
    'Panthera ',
    'Papahānaumoku',
    'Paralian',
    'Pasargadae',
    'Pascal',
    'Pelagus',
    'Pele',
    'Penghou ',
    'Penglai',
    'Penumbra',
    'Persephone',
    'Perses',
    'Perwana',
    'Peryton',
    'Petbe',
    'Philotimo',
    'Phoebe',
    'Phoenix ',
    'Phontes ',
    'Picon ',
    'Pinga',
    'Pirx  ',
    'Pitch',
    'Pohjola',
    'Poliʻahu',
    'Polyphemus',
    'Pontus',
    'Pooka ',
    'Poseidon',
    'Pratāpana',
    'Prime',
    'Prometheus',
    'Ptah',
    'Purson',
    'Pyaar',
    'Pyrrus',
    'Qailertetang',
    'Qamata',
    'Quivira',
    'Ra',
    'Rain',
    'Ram Setu',
    'Ramajay ',
    'Raphael',
    'Rapture',
    'Raurava ',
    'Ré nao',
    'Reach',
    'Rebirth',
    'Refuge',
    'Regis',
    'Rem',
    'Renenutet',
    'Resheph',
    'Rhea',
    'Rhiannon ',
    'Rhodes',
    'Riosar  ',
    'River',
    'Rocinante  ',
    'Rokot',
    'Roog',
    'Rudianos ',
    'Ruhe',
    'Rust',
    'Rylos',
    'Ryn',
    'Sabbat',
    'Sabaism',
    'Safir',
    'Sah',
    'Salawa ',
    'Salem',
    'Saleos',
    'Salt',
    'Samael',
    'Samagiya  ',
    'Samavasarana  ',
    'Saṃghāta',
    'Samsara',
    'Sangre ',
    'Sañjīva',
    'Santamasa ',
    'Santokh',
    'Sarangay',
    'Sardis',
    'Sat',
    'Saur',
    'Sauria',
    'Schadenfreude',
    'Scholomance  ',
    'Sebiumeker',
    'Sedna ',
    'Seiren',
    'Seker',
    'Selket ',
    'Sera',
    'Seraphim',
    'Serapis',
    'Seshat',
    'Shai',
    'Shango',
    'Shangri-La',
    'Shanshen',
    'Shavit',
    'Shed',
    'Shenron',
    'Shesmetet',
    'Shora',
    `Shtil'`,
    'Shu',
    'Sihnon',
    'Silence ',
    'Simorgh',
    'Simurgh ',
    'Sindri',
    'Skaro',
    'Sky',
    'Sleipnir ',
    'Smaug',
    'Smertrios',
    'Smoke Ring',
    'Sobek',
    'Solaris',
    'Solstice',
    'Sopdet',
    'Soyuz',
    'Spe',
    'Sphinx',
    'Sputnik',
    'Staburags ',
    'Stheno ',
    'Strela',
    'Strix ',
    'Stygia',
    'Suddene',
    'Suen ',
    'Sukha',
    'Sul ',
    'Surt',
    'Svarga',
    'Svartálfaheimr',
    'Tadmor',
    'Takhar',
    'Talon',
    'Tamoanchan',
    'Tanit',
    'Tapana',
    'Taranus',
    'Tartarus',
    'Tatenen',
    'Taweret',
    'Tefnut',
    'Terminus',
    'Tesla',
    'Teutates ',
    'Thalassa',
    'Thanatos',
    'The Tooth',
    'Theia',
    'Themis',
    'Themiscyra',
    'Thessia',
    'Thestius',
    'Thetis',
    'Thor',
    'Thoth',
    'Three Jewels',
    'Throne',
    'Thule',
    'Thunor ',
    'Tia ',
    'Tilberi',
    'Tír na nÓg',
    'Tiratana',
    'Tiurakh',
    'Tohil',
    'Tōnacācihuātl',
    'Tongnaab',
    'Toska',
    'Trantor',
    'Trees',
    'Triratna',
    'Triumph',
    'Trojan',
    'Tsyklon ',
    'Tuatha',
    'Tuchanka ',
    'Tulpa ',
    'Tutu',
    'Twinsun',
    'Tzitzimitl',
    'Ultron ',
    'Umbäässa ',
    'Umbra',
    'Undine ',
    'Unha',
    'Unicorn ',
    'Unity',
    'Unkulunkulu',
    'Ursae',
    'Utpala',
    'Utu',
    'Vahagn ',
    'Valefar',
    'Valhalla',
    'Valinor',
    'Vanaheimr',
    'Vapula',
    'Veles  ',
    'Vellichor',
    'Venom',
    'Verbena',
    'Verde',
    'Vesi',
    'Viculus ',
    'Vieneo',
    'Vine',
    'Vinea',
    'Viriato ',
    'Virtue',
    'Vishnu',
    'Vlekete',
    'Volna',
    'Voskhod ',
    'Vostok',
    'Vual',
    'Vulpes',
    'Wadj-wer',
    'Welaahilaninui',
    'Wepset',
    'Weyland',
    'Whitefall',
    'Woden ',
    'Wolf',
    'Worlorn',
    'Wormwood',
    'Wosret',
    'Xamaba',
    'Xōchiquetzal',
    'Xbaquiyalo',
    'Yggdrasil',
    'Yohaulticetl',
    'Yopaat',
    'Ys',
    'Yu Yi',
    'Yuputka ',
    'Yushen',
    'Zadkiel',
    'Zagan',
    'Zahir',
    'Zamba',
    'Zarathustra',
    'Zeitgeist',
    'Zenenet',
    'Zenith',
    'Zenosyne',
    'Zerachiel',
    'Zerzura',
    'Zeus',
]